### ISSUE TITLE
How to implement on SSR

### ISSUE THREAD

**Issue by Beatusvir** [vuejs/vue-touch#59]
Hey guys, I'm trying to use this (for vue2 using vue-touch@next) in a project based on [Isomorphic Vue](https://github.com/egoist/vue-isomorphic-starter) and I'm getting an error about window not being defined, so my guess is I'm trying to load this before the client side has been rendered/created. Any tips on how I should use this?

This was my previous code:
```
// main.js
import Vue from 'vue';
import VueRouter from 'vue-router';
import VueTouch from 'vue-touch';
import { configRouter } from './route-config';
require('es6-promise').polyfill()

Vue.use(VueRouter);
Vue.use(VueTouch);


const router = new VueRouter({
  history: true,
  saveScrollPosition: true,
});

configRouter(router);

const App = Vue.extend(require('./App.vue'));

router.start(App, '#app');

window.router = router;
```

New `main.js` file from isomorphic project
```
// main.js
import { app, store } from './app.js'

// get the initialstate from server-rendering.
store.replaceState(window.__INITIAL_STATE__)

app.$mount('#app')
```

This is where I tried to use VueTouch without success, getting the error `window is not defined`
```
// app.js
import Vue from 'vue'
import VueTouch from 'vue-touch'
import {sync} from 'vuex-router-sync'
import App from './App.vue'
import router from './router/index.js'
import store from './vuex/store.js'

sync(store, router)

const app = new Vue({
  router,
  store,
  ...App
})

Vue.use(VueTouch)
export {app, router, store}
```

I know this is not related to vue touch but to my project config, so I thought this is good place to ask as any, thanks

**Comment by LinusBorg** [comment]
Well, your problem is not vue.touch, it's this line:

> store.replaceState(window.__INITIAL_STATE__)

Which should not be in the isomorphic main.js - you need a separate `client-entry.js` and `server-entry.js` from which you can build seperate client-side and server-side bundles. and the above code belongs in the client-entry.js

Look at vue-hackernew-2.0 example:
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/client-entry.js
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/server-entry.js

Please ask for further support on forum.vuejs.org, not here.
