### ISSUE TITLE
Error SSR with v2.0.0-beta.3 Unexpected token: name (Hammer)

### ISSUE THREAD

**Issue by ram-you** [vuejs/vue-touch#72]
I tried the solution:
```
alias: {
  'hammerjs$': 'vue-touch/dist/hammer-ssr.js'
}
```
Error after compilation: 

> ERROR in app.e58c50a4d0f7aa688e35.js from UglifyJs
> SyntaxError: Unexpected token: name (Hammer)

**Comment by LinusBorg** [comment]
Problem: I'm an idiot and didn't transpile the file. UglifyJS chokes on the ES6 class definition inside.

Should be easy to fix.

**Comment by LinusBorg** [comment]
@ram-you A quick side question: Why are you using uglifyJS on the server?

**Comment by ram-you** [comment]
@LinusBorg  My project have the vuejs/vue-hackernews-2.0 as Boilerplate. Here the source of using uglifyJS : 
https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/webpack.client.config.js

**Comment by LinusBorg** [comment]
You should include that alias *only* in the `webpack.server.config.js`, because it replaces the original Hammer module with an empty shell -and you do need the real thing in the client, right?

Seems that I should make that more clear in the README.

*Note: This won't solve the source of the reported issue, of course. I still have to fix that*

**Comment by LinusBorg** [comment]
hopefully solved in 2.0.0-beta.4
